apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-todo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-todo
  template:
    metadata:
      labels:
        app: django-todo
    spec:
      containers:
      - name: django-todo
        image: bishalr0y/my-app:django-todo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name:  docker-hub-cred


# to create the secret

# kubectl create secret docker-registry docker-hub-cred \
# --docker-username username \
# --docker-password password